# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='severity',
        ),
    ]
