# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_task_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='severity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
